stages:
  - build

.buildkit:
  image:
    name: moby/buildkit:rootless
    entrypoint: [""]
  stage: build
  variables:
    BUILDKITD_CONFIG: /tmp/buildkitd.toml
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox --config /tmp/buildkitd.toml
    BUILDKIT_FRONTEND: dockerfile.v0
    BUILDKIT_CONTEXT: .
    BUILDKIT_DOCKERFILE_DIR: .
    BUILDKIT_IMAGE_NAME: $CI_REGISTRY_IMAGE
    BUILDKIT_IMAGE_TAG: $CI_COMMIT_SHA
    BUILDKIT_OUTPUT_TYPE: image
    BUILDKIT_PUSH: "true"
    BUILDKIT_CACHE_REF: $CI_REGISTRY_IMAGE:buildcache
  before_script:
    - mkdir -p ~/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > ~/.docker/config.json
    - |
      cat > "$BUILDKITD_CONFIG" <<'EOF'
      [registry."docker.io"]
        insecure = true
      EOF
  script:
    - |
      buildctl-daemonless.sh build \
        --frontend "${BUILDKIT_FRONTEND}" \
        --local context="${BUILDKIT_CONTEXT}" \
        --local dockerfile="${BUILDKIT_DOCKERFILE_DIR}" \
        --import-cache type=registry,ref="${BUILDKIT_CACHE_REF}" \
        --export-cache type=registry,ref="${BUILDKIT_CACHE_REF}",mode=max \
        --output type="${BUILDKIT_OUTPUT_TYPE}",name="${BUILDKIT_IMAGE_NAME}:${BUILDKIT_IMAGE_TAG}",push="${BUILDKIT_PUSH}"

build-image:
  extends: .buildkit
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
